run:
  timeout: 3m
  tests: true
linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - prealloc
    - gocritic
issues:
  exclude-use-default: false
